{% set name = "pyttk" %}
{% set version = "0.3.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '5ac911938d0b08280432badc0b46f4dbc37c5567364191a9374a7b654c4f6d02'

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - tk

test:
  requires:
    - python {{ python_min }}
  imports:
    ttk

about:
  home: http://code.google.com/p/python-ttk
  license: LGPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: Ttk Python wrapper
  description: |
    This ttk wrapper provides classes to allow using the Tk themed widget
    set, as well some extensions, under Python.  Ttk is based on a revised
    and enhanced version of TIP #48 (http://tip.tcl.tk/48) specified style
    engine.  Its basic idea is to separate, to the extent possible, the code
    implementing a widget's behavior from the code implementing its
    appearance. Widget class bindings are primarily responsible for
    maintaining the widget state and invoking callbacks, all aspects of the
    widgets appearance lies at Themes.

extra:
  recipe-maintainers:
    - smithsp
